esphome:
  name: "humidifier"
  friendly_name: "humidifier"

esp8266:
  board: esp12e

# Enable logging
logger:
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: "4RJaFJBugiEqBHp5yEDpQVlvNXIOsYNCtiUoOJDoWnI="

ota:
  password: "0c21514011fbd50e9c6f5ea088b01363"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test1 Fallback Hotspot"
    password: "YAcSmWqgVWYJ"

captive_portal:
    
dallas:
  - pin: GPIO16


uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:


switch:
  - platform: tuya
    name: "Power"
    switch_datapoint: 10

  - platform: tuya
    name: "Night mode"
    switch_datapoint: 103

  - platform: tuya
    name: "Auto mode"
    switch_datapoint: 104

binary_sensor:
  - platform: tuya
    name: "Water level"
    sensor_datapoint: 101
  
  - platform: tuya
    name: "Change filter"
    sensor_datapoint: 107

sensor:
  - platform: tuya
    sensor_datapoint: 109
    name: "Current humidity"
    device_class: humidity
  - platform: dallas
    index: 0
    name: "Current temperature"


select:
  - platform: tuya
    name: "Target humidity"
    icon: "mdi:fan"
    enum_datapoint: 105
    options:
      0: "Off"
      1: "40"
      2: "45"
      3: "50"
      4: "55"
      5: "60"
      6: "65"
      7: "70"
      8: "75"
  - platform: tuya
    name: "Light"
    icon: "mdi:lightbulb"
    enum_datapoint: 102
    options:
      0: "Off"
      1: "Low"
      2: "Medium"
      3: "High"
  - platform: tuya
    name: "Fan speed"
    icon: "mdi:fan"
    enum_datapoint: 106
    options:
      0: Low
      1: Medium
      2: High
      3: Turbo
  - platform: tuya
    name: "Timer"
    icon: "mdi:timer"
    enum_datapoint: 108
    options:
      0: 'Off'
      1: '1h'
      2: '2h'
      3: '3h'
      4: '4h'
      5: '5h'
      6: '6h'
      7: '7h'
      8: '8h'
      9: '9h'
      10: '10h'
      11: '11h'
      12: '12h'